"""Generate formatted Excel take-off reports from TakeoffResult data."""

import logging
from datetime import datetime
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

logger = logging.getLogger(__name__)

# ── Palette ──────────────────────────────────────────────────────────────────
C = {
    "navy": "1F3864",
    "navy_fg": "FFFFFF",
    "blue": "2F75B6",
    "blue_fg": "FFFFFF",
    "light_blue": "BDD7EE",
    "row_alt": "F2F7FB",
    "green": "E2EFDA",
    "yellow": "FFF2CC",
    "orange": "FCE4D6",
    "red": "C00000",
    "red_light": "FFE0E0",
    "white": "FFFFFF",
}

THIN = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin"),
)

CONF_COLOR = {
    "high": C["green"],
    "medium": C["yellow"],
    "low": C["orange"],
}


def _font(bold=False, size=10, color="000000", italic=False):
    return Font(name="Calibri", size=size, bold=bold, color=color, italic=italic)


def _fill(hex_color: str):
    return PatternFill("solid", fgColor=hex_color)


def _center(wrap=False):
    return Alignment(horizontal="center", vertical="center", wrap_text=wrap)


def _left(wrap=False):
    return Alignment(horizontal="left", vertical="center", wrap_text=wrap)


def _right():
    return Alignment(horizontal="right", vertical="center")


# ── Reporter ──────────────────────────────────────────────────────────────────

class ExcelReporter:
    """Generates a multi-sheet Excel take-off workbook."""

    def generate(self, result, output_path: str | Path) -> Path:
        output_path = Path(output_path)
        wb = openpyxl.Workbook()
        wb.remove(wb.active)

        self._summary_sheet(wb, result)
        self._takeoff_sheet(wb, result)
        self._detail_sheets(wb, result)

        wb.save(str(output_path))
        logger.info(f"Excel report saved: {output_path}")
        return output_path

    # ── Summary sheet ─────────────────────────────────────────────────────────

    def _summary_sheet(self, wb, result):
        ws = wb.create_sheet("Summary")
        ws.column_dimensions["A"].width = 26
        ws.column_dimensions["B"].width = 48

        r = 1

        # Title banner
        ws.merge_cells(f"A{r}:B{r}")
        c = ws[f"A{r}"]
        c.value = "ARCHITECTURAL TAKE-OFF REPORT"
        c.font = _font(bold=True, size=16, color=C["navy_fg"])
        c.fill = _fill(C["navy"])
        c.alignment = _center()
        ws.row_dimensions[r].height = 32
        r += 1

        # Generated by
        ws.merge_cells(f"A{r}:B{r}")
        c = ws[f"A{r}"]
        c.value = f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  AI Take-Off Agent"
        c.font = _font(italic=True, size=9, color="555555")
        c.alignment = _center()
        r += 2

        # Project / drawing metadata
        title_block = result.title_block or {}
        fields = []
        if title_block.get("project_name"):
            fields.append(("Project", title_block["project_name"]))
        if title_block.get("drawing_number"):
            fields.append(("Drawing No.", title_block["drawing_number"]))
        if title_block.get("drawing_title"):
            fields.append(("Drawing Title", title_block["drawing_title"]))
        if title_block.get("date"):
            fields.append(("Drawing Date", title_block["date"]))

        fields += [
            ("Source File", Path(result.drawing_path).name),
            ("Drawing Type", result.drawing_type.replace("_", " ").title()),
            ("Scale", result.scale or "Not determined"),
            ("Overall Confidence", result.overall_confidence.upper()),
        ]

        for label, value in fields:
            lc = ws[f"A{r}"]
            vc = ws[f"B{r}"]
            lc.value = label
            lc.font = _font(bold=True)
            vc.value = str(value)
            vc.font = _font()

            if label == "Overall Confidence":
                col = CONF_COLOR.get(str(value).lower(), C["white"])
                vc.fill = _fill(col)
                vc.font = _font(bold=True)

            for cell in (lc, vc):
                cell.border = THIN
                cell.alignment = _left()
            r += 1

        r += 1

        # Category summary
        categories: dict[str, list] = {}
        for item in result.line_items:
            categories.setdefault(item.get("category", "Other"), []).append(item)

        if categories:
            ws.merge_cells(f"A{r}:B{r}")
            c = ws[f"A{r}"]
            c.value = "QUANTITY SUMMARY BY CATEGORY"
            c.font = _font(bold=True, color=C["blue_fg"])
            c.fill = _fill(C["blue"])
            c.alignment = _center()
            c.border = THIN
            ws[f"B{r}"].border = THIN
            r += 1

            for cat, items in categories.items():
                lc = ws[f"A{r}"]
                vc = ws[f"B{r}"]
                lc.value = cat
                lc.font = _font(bold=True)
                lc.fill = _fill(C["light_blue"])
                lc.border = THIN
                lc.alignment = _left()

                total_qty = sum(
                    i["quantity"] for i in items if isinstance(i.get("quantity"), (int, float))
                )
                units = {i.get("unit", "EA") for i in items}
                unit_str = "/".join(sorted(units))
                vc.value = f"{total_qty:,.1f} {unit_str}" if total_qty != int(total_qty) else f"{int(total_qty):,} {unit_str}"
                vc.font = _font()
                vc.fill = _fill(C["light_blue"])
                vc.border = THIN
                vc.alignment = _left()
                r += 1

        r += 1

        # Estimator notes
        if result.estimator_notes:
            ws.merge_cells(f"A{r}:B{r}")
            c = ws[f"A{r}"]
            c.value = "ESTIMATOR NOTES"
            c.font = _font(bold=True, color=C["navy_fg"])
            c.fill = _fill(C["navy"])
            c.alignment = _center()
            c.border = THIN
            ws[f"B{r}"].border = THIN
            r += 1

            ws.merge_cells(f"A{r}:B{r}")
            c = ws[f"A{r}"]
            c.value = result.estimator_notes
            c.font = _font()
            c.alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)
            c.border = THIN
            ws.row_dimensions[r].height = max(60, len(result.estimator_notes) // 2)
            ws[f"B{r}"].border = THIN
            r += 1

        # Verification items
        if result.verification_items:
            r += 1
            ws.merge_cells(f"A{r}:B{r}")
            c = ws[f"A{r}"]
            c.value = "⚠  ITEMS REQUIRING FIELD VERIFICATION"
            c.font = _font(bold=True, color=C["navy_fg"])
            c.fill = _fill(C["red"])
            c.alignment = _center()
            c.border = THIN
            ws[f"B{r}"].border = THIN
            r += 1

            for vi in result.verification_items:
                ws[f"A{r}"].value = "▸"
                ws[f"B{r}"].value = vi
                for col in ("A", "B"):
                    cell = ws[f"{col}{r}"]
                    cell.font = _font()
                    cell.fill = _fill(C["red_light"])
                    cell.border = THIN
                    cell.alignment = _left(wrap=True)
                r += 1

    # ── Main take-off sheet ───────────────────────────────────────────────────

    def _takeoff_sheet(self, wb, result):
        ws = wb.create_sheet("Take-Off")

        col_widths = [4, 20, 12, 46, 12, 7, 12, 42]
        headers = ["#", "Category", "Item Code", "Description", "Quantity", "Unit", "Confidence", "Notes"]

        for i, (w, h) in enumerate(zip(col_widths, headers), start=1):
            ws.column_dimensions[get_column_letter(i)].width = w
            c = ws.cell(row=1, column=i, value=h)
            c.font = _font(bold=True, color=C["navy_fg"])
            c.fill = _fill(C["navy"])
            c.alignment = _center()
            c.border = THIN

        ws.row_dimensions[1].height = 20
        ws.freeze_panes = "A2"

        # Group by category
        categories: dict[str, list] = {}
        for item in result.line_items:
            categories.setdefault(item.get("category", "Other"), []).append(item)

        row = 2
        seq = 1

        for category, items in categories.items():
            # Category header
            ws.merge_cells(f"A{row}:H{row}")
            c = ws[f"A{row}"]
            c.value = f"  {category.upper()}"
            c.font = _font(bold=True, color=C["blue_fg"], size=10)
            c.fill = _fill(C["blue"])
            c.alignment = _left()
            c.border = THIN
            ws.row_dimensions[row].height = 18
            row += 1

            for item in items:
                alt = seq % 2 == 0
                conf = (item.get("confidence") or "medium").lower()
                qty = item.get("quantity", 0)

                values = [
                    seq,
                    item.get("category", ""),
                    item.get("item_code", ""),
                    item.get("description", ""),
                    qty,
                    item.get("unit", ""),
                    conf.upper(),
                    item.get("notes", ""),
                ]

                for col_i, val in enumerate(values, start=1):
                    c = ws.cell(row=row, column=col_i, value=val)
                    c.font = _font(size=10)
                    c.border = THIN

                    if col_i == 7:  # Confidence
                        c.fill = _fill(CONF_COLOR.get(conf, C["white"]))
                        c.font = _font(bold=True, size=10)
                        c.alignment = _center()
                    elif col_i == 5:  # Quantity
                        c.alignment = _right()
                        c.number_format = "#,##0.0" if isinstance(qty, float) and qty != int(qty) else "#,##0"
                        if alt:
                            c.fill = _fill(C["row_alt"])
                    elif col_i == 8:  # Notes
                        c.alignment = _left(wrap=True)
                        if alt:
                            c.fill = _fill(C["row_alt"])
                    else:
                        c.alignment = _left()
                        if alt:
                            c.fill = _fill(C["row_alt"])

                ws.row_dimensions[row].height = 15
                row += 1
                seq += 1

            row += 1  # blank spacer between categories

    # ── Detail sheets ─────────────────────────────────────────────────────────

    def _detail_sheets(self, wb, result):
        partition = result.raw_data.get("extract_partition_data")
        rcp = result.raw_data.get("extract_rcp_data")
        if partition:
            self._partition_detail(wb, partition)
        if rcp:
            self._rcp_detail(wb, rcp)

    def _partition_detail(self, wb, data: dict):
        ws = wb.create_sheet("Partition Detail")
        widths = [15, 42, 12, 15, 12, 32]
        for i, w in enumerate(widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = w

        r = 1
        ws.merge_cells(f"A{r}:F{r}")
        c = ws[f"A{r}"]
        c.value = "PARTITION PLAN — WALL TYPE QUANTITIES"
        c.font = _font(bold=True, size=13, color=C["navy_fg"])
        c.fill = _fill(C["navy"])
        c.alignment = _center()
        ws.row_dimensions[r].height = 26
        r += 2

        r = self._section_header(ws, r, "WALL TYPES", 6)
        for i, label in enumerate(
            ["Type ID", "Description", "Linear Metres (LM)", "Height", "Fire Rating", "Notes"], 1
        ):
            c = ws.cell(row=r, column=i, value=label)
            c.font = _font(bold=True)
            c.fill = _fill(C["light_blue"])
            c.border = THIN
        r += 1

        for wall in data.get("walls", []):
            row_data = [
                wall.get("type_id", ""),
                wall.get("description", ""),
                wall.get("estimated_linear_metres", 0),
                wall.get("height", ""),
                wall.get("fire_rating", ""),
                wall.get("notes", ""),
            ]
            for i, val in enumerate(row_data, 1):
                c = ws.cell(row=r, column=i, value=val)
                c.border = THIN
                c.font = _font()
                c.alignment = _right() if i == 3 else _left(wrap=(i in (2, 6)))
            r += 1

    def _rcp_detail(self, wb, data: dict):
        ws = wb.create_sheet("RCP Detail")
        widths = [15, 42, 12, 16, 32]
        for i, w in enumerate(widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = w

        r = 1
        ws.merge_cells(f"A{r}:E{r}")
        c = ws[f"A{r}"]
        c.value = "REFLECTED CEILING PLAN — CEILING TYPE QUANTITIES"
        c.font = _font(bold=True, size=13, color=C["navy_fg"])
        c.fill = _fill(C["navy"])
        c.alignment = _center()
        ws.row_dimensions[r].height = 26
        r += 2

        r = self._section_header(ws, r, "CEILING TYPES", 5)
        for i, label in enumerate(["Type ID", "Description", "Area (m²)", "Height AFF", "Notes"], 1):
            c = ws.cell(row=r, column=i, value=label)
            c.font = _font(bold=True)
            c.fill = _fill(C["light_blue"])
            c.border = THIN
        r += 1

        for ceiling in data.get("ceiling_types", []):
            row_data = [
                ceiling.get("type_id", ""),
                ceiling.get("description", ""),
                ceiling.get("estimated_area_m2", 0),
                ceiling.get("height_aff", ""),
                ceiling.get("notes", ""),
            ]
            for i, val in enumerate(row_data, 1):
                c = ws.cell(row=r, column=i, value=val)
                c.border = THIN
                c.font = _font()
                c.alignment = _right() if i == 3 else _left(wrap=(i in (2, 5)))
            r += 1

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _section_header(self, ws, row: int, title: str, span: int) -> int:
        end_col = get_column_letter(span)
        ws.merge_cells(f"A{row}:{end_col}{row}")
        c = ws[f"A{row}"]
        c.value = f"  {title}"
        c.font = _font(bold=True, color=C["blue_fg"])
        c.fill = _fill(C["blue"])
        c.alignment = _left()
        c.border = THIN
        ws.row_dimensions[row].height = 18
        for i in range(2, span + 1):
            ws.cell(row=row, column=i).border = THIN
        return row + 1
